default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: your_username
  password: your_password
  host: localhost

development:
  <<: *default
  database: online_store_development

test:
  <<: *default
  database: online_store_test

production:
  <<: *default
  database: online_store_production
  username: online_store
  password: <%= ENV['ONLINE_STORE_DATABASE_PASSWORD'] %>
